version: "3"

services:
  node-app:
    build: .
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules/
    networks:
      - app-network
  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: books_user
      MYSQL_DATABASE: books
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge