version: "3"

services:

  node-app1:
    build: .
    container_name: node-app1
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules/
    networks:
      - app-network

  node-app2:
    build: .
    container_name: node-app2
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      APP_NAME: 'app-2'
    ports:
      - "8082:8080"
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules/
    networks:
      - app-network

  nginx:
    image: nginx:1.17.5
    container_name: nginx
    depends_on:
      - node-app1
      - node-app2
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: books_user
      MYSQL_DATABASE: books
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge